### ISSUE TITLE
Increase the block.number instead of timestamp of EVM

### ISSUE THREAD

**Issue by satyamakgec** [WandXDapp/WandX-Options#4]
@Dinesh2521 do you know how to increase the block number in testrpc. It is required to complete the test cases

**Comment by satyamakgec** [comment]
@ksridharbabuus, please provide your inputs as well

**Comment by ksridharbabuus** [comment]
As per my knowledge we will not have the control over the Block Number in the testRPC.
Other alternate way is to use time parameter for TestRPC to specify the first Block Start time and remaining sub subsequent blocks will be created as the transactions progresses. You can along with evm_increateTime & evm_mine to do any time dependent testing.
I will suggest to do the test in real test network rather than with testRPC especially for validating block number dependent use cases.
Hope this helps.

**Comment by ksridharbabuus** [comment]
BTW you can also look at --blocktime parameter to specify the time required to mine the block.

**Comment by satyamakgec** [comment]
@ksridharbabuus I think both of the ideas may not work because 

Case 1 :
If we can opt the `--blocktime ` parameter then we only know how much time it takes to mine the block + if we take the initial timestamp of the testrpc and then use the `evm_increaseTime` to increase the time and then we calculate on the basis of above three value it gives us something but not much that will verify the condition in the smart contract `require(expiry>block.number)` because it doesn't increase the block number at all only increase the  timestamp of the `evm`.  As per my knowledge, it increases the timestamp of the next block mined not mine as many blocks to reach the predictive timestamp. 

Case 2:
For `evm_mine` it is only used to mine the current block not to increase the block number or mine the block numbers according to the no. of the block provided. so I think it is not useful at all.

Case 3:
For ropsten testing, Yes we can do that by providing the small `block.number` difference. Maybe this way we are not able to test the real behavior of the smart contracts. It will only give the predictive behavior

**Comment by satyamakgec** [comment]
Test the withdraw function directly on ropsten
